### ISSUE TITLE
Activating for *.rst files

### ISSUE THREAD

**Issue by jakubka** [swyphcosmo/vscode-spellchecker#1]
Hi,

Thanks for the good work with the extension!

It works well with .md files, but I am having troubles activating it for *.rst (reStructuredText) files. *.rst should be interpreted as 'plaintext', so I assumed it will be picked up by default, but it wasnt..

I tried adding spellchecker.json and explicitly specifying plaintext in documentTypes, but no luck.. I then tried associating *.rst with markdown languageid, but again no luck.

What am I doing wrong? Thanks!

**Comment by jakubka** [comment]
And suddenly it started working, no idea why. :) I have

```
"documentTypes": [
    "markdown"
],
```

in spellchecker.json. And

```
"files.associations": {
    "*.rst": "markdown"
}
```

in settings.json.

**Comment by swyphcosmo** [comment]
Without the `spellchecker.json` file, the `documentTypes` variable defaults to checking `markdown`, `latex`, and `plaintext`. I think what caused it to work in your case is the `files.associations` in `settings.json`. Any settings changed in `spellchecker.json` require you to restart VSCode. I think the changes in `settings.json` will be automatically updated. 

I'm glad you're enjoying the extension!

**Comment by davidovich** [comment]
I also had a problem setting `spellchecker.documentTypes` to `"reStructuredText"`. The extension does not work in that case. I have to add `files.associations` as @jakubka proposed. I think this is not the correct fix, although being a working workaround.

Shouldn't `spellchecker.documentTypes` respect the detected documentType of vscode ?

**Comment by swyphcosmo** [comment]
There was a command added a while ago that will show the documentType for the current file. `CTRL + SHIFT + P`, type `documentType`. The command is "Show documentType for Current File". 

The documentType display in the bottom right corner of VSCode is typically the human readable format of the type and not the one that is used internally. For this case, the documentType for a .rst file is "restructuredtext" (notice that it's all lower case). If you add that string to `spellchecker.documentTypes`, then your file should be spell checked.  

I don't use reStructuredText, so if you run into any issues where it's not checking certain sections or doing anything weird, let me know by opening a new issue.

**Comment by davidovich** [comment]
hmm, documentType from the command palette tells me `The documentType for the current file is 'testOutput'.`

But adding `"restructuredtext"` in the settings seems to be working. Thanks. I believe this is how it should be.

**Comment by swyphcosmo** [comment]
I ran into some issues with it showing the wrong thing when I was just testing it. I closed down all of the other open documents. I'll look into what's causing this issue. Hopefully, I can get it into the next release.

Glad it's working now.
