### ISSUE TITLE
Add "Always Ignore" in addition to "Add to Dictionary"

### ISSUE THREAD

**Issue by randomchance** [swyphcosmo/vscode-spellchecker#2]
It would be really convenient if you could add **"Always Ignore"** to the corrections menu. Ideally it would save to the workspace level `spellchecker.json`, but even if it saved to a user level one it would be really nice to have integrated.

Thanks for the great extension btw!

**Comment by swyphcosmo** [comment]
I finally made time to add this feature. Now, the `Add to Dictionary` function will save the words to the settings.json file in the workspace. I've also added an `Always Ignore` option to the suggestions list. This will save to the User Preferences `settings.json`. Thanks for the suggestion!
