### ISSUE TITLE
Words containing specific characters are recognised, but give no context menu

### ISSUE THREAD

**Issue by darkmattercoder** [swyphcosmo/vscode-spellchecker#25]
When I have words like "abcde²fg", they are marked as misspelled, but I am unable to get the lightbulb for that word. Manually adding such words to the ignore-list, does not change this.

The same applies for words containing German umlauts and other language-dependent special characters.

I know that the extension is only supposed to work with english texts atm. But I have a file where several paragraphs are not yet translated whereas others are. 

Unfortunately, when the German paragraphs contain more than the maximum of ~250 misspellings, the whole rest of the document, is not checked  anymore. I really want to add all those German words to the ignore list, but the frequent usage of umlauts in German texts is blocking that.

I even see the spellchecker in the log recognising the words and logging suggestions for them, regardless if they contain such characters.

Example for checking: "Spelling [ motör ]: suggestions [ motor, mother, mots, moth, moo ]"

But the code 

```
// Get word
let match:string[] = diagnostic.message.match( /\[\ ([a-zA-Z0-9]+)\ \]\:/ );
let word:string = '';

// should always be true
if( match.length >= 2 )
	word = match[ 1 ];

	if( word.length == 0 )
		return undefined;
```

 prevents the lightbulb to show.

Any ideas if that could be fixed easily?

Jochen

**Comment by swyphcosmo** [comment]
Jochen, Thanks for looking into this so in depth. I will try to get this fixed in the next few days. If you want to submit a pull request sooner than that, I'd be happy to merge it.

**Comment by rotemdan** [comment]
Apostrophes/single quotes seem to cause this behavior as well, for example:

```
This is Grumpy's dinner.
```
`Grumpy's` is highlighted as a spelling mistake and details are shown on hover but the light bulb doesn't appear when it is clicked.

Removing the apostrophe causes the light bulb to correctly appear.

**Comment by swyphcosmo** [comment]
Yes, this is the same issue. Thanks for reminding me to fix it. I'll get a fix out today.
