### ISSUE TITLE
Where is the global dictionary stored?

### ISSUE THREAD

**Issue by laggingreflex** [swyphcosmo/vscode-spellchecker#26]
I accidentally added an incorrect speling in the global dictionary that I need to remove. Where is the global dictionary stored?

Awesome extension btw!

**Comment by swyphcosmo** [comment]
It depends on how you added the word:

* If you did "Ignore", go to `.vscode/spellchecker.json` within your workspace
* If you did "Always Ignore", go to your user preferences `settings.json`. File -> Preferences -> User Settings.

Thanks for using the extension! Hopefully, this helps fix your problem
