### ISSUE TITLE
"Add to dictionary" / "Always ignore" ambiguity

### ISSUE THREAD

**Issue by rotemdan** [swyphcosmo/vscode-spellchecker#30]
In most spellcheckers "Add to dictionary" means to "Add to global dictionary" and "ignore" usually means "ignore for this document". Here, the meaning/usage seems to be reversed so I'll try to give some alternative suggestions:

Option 1:
* `Add to dictionary` is changed to `Add to workspace dictionary`.
* `Always ignore` stays the same or changed to `Add to global dictionary`.

Option 2:
* `Add to dictionary` is changed to `Ignore for this workspace` or the more grammatically correct `Ignore at this workspace`.
* `Always ignore` is changed to `Add to dictionary`.

The second option is the most consistent with other spellcheckers, and I feel captures the meaning better, but might be a "breaking change" for current users of the extension (though I'm not sure how popular it is at the time of this writing, so maybe the effect wouldn't be that serious).

_Edit:_

In any case, to keep the codefix popup menu from getting too wide maybe omit the target word in the menu option: instead of `Add '...' to dictionary` just use `Add to dictionary`, same for `Ignore at this workspace`. (_Edit 2:_ on second thought since the popup menu isn't positioned exactly above the word I'm not sure if this is the best idea, so I'm undecided about this..).

**Comment by rotemdan** [comment]
This UX Stack Exchange question gives examples from 6 different spell checkers (Google Drive, Word, Zoho Docs, Pages, Evernote) on how `Ignore` / `Ignore all` / `Add to dictionary` are used:

https://ux.stackexchange.com/questions/83396/what-does-ignore-and-ignore-all-really-mean-in-spell-check

In all examples `Ignore all` means "ignore all occurrences at this document" and `Add to dictionary` means to permanently remember the spelling so it is always ignored in all documents. There are other variations as well like `Learn spelling`, `Always correct to..`.

**Comment by swyphcosmo** [comment]
I understand the ambiguity. I'll look at options and see about integrating them into an upcoming release. Thanks for doing the background research.

**Comment by swyphcosmo** [comment]
Changing to "Ignore" and "Always Ignore" in the next release. This should be out in the next day or two.
