### ISSUE TITLE
Add support for French language (contribution offer)

### ISSUE THREAD

**Issue by adrienjoly** [swyphcosmo/vscode-spellchecker#31]
Hi!

I love vscode, but keep using SublimeText just because it has an offline spellcheck extension for the French language: https://github.com/superbob/SublimeTextLanguageFrench

Being a developer myself, I would be happy to contribute to your project (or start a new one, if you think that it makes more sense), so that I can run offline spellchecking for my French documents from vscode.

Do you have any suggestions to provide, on how I/we could do that?

**Comment by swyphcosmo** [comment]
Adding more languages is something that I've had on my list for a while, but I haven't made the time for it. 

All it takes to add a new language is to add a Hunspell compatible dictionary (`.dic` and `.aff` files) to the `/languages` directory in this repo. 

One drawback of this is that the language files are pretty big (relative to the rest of the files in the extension). A person will have every language installed independent of which ones they use. I've been thinking about adding the ability to download the language selectively based on what is used. There's a great repository of dictionary files maintained by wooorm https://github.com/wooorm/dictionaries. He also has a lot of packages that I've been looking to integrate to increase the functionality of this extension.

It might be a while before I get around to adding this functionality, so feel free to submit a PR in the mean time

**Comment by adrienjoly** [comment]
Hi @swyphcosmo!

Thanks for your reply!

I tried that (you can [watch me do it](https://www.youtube.com/watch?v=QFrkLEzb2Lo)), but ended up having a blocking error after adding FR dictionary files...

Here's a journal of what I did:

### Add a French spellchecker to Visual Studio Code

Steps:

- [x] Install and test existing extension: vscode-spellchecker 
- [x] Fork vscode-spellchecker and make it work locally
- [ ] Integrate a French dictionary (Hunspell .dic/.aff files)
- [ ] Package the fork as an extension
- [ ] Pull Request vscode-spellchecker
- [ ] Don't need to use SublimeText anymore to edit my markdown files! \o/

Journal:

- problem: the extension was not working
- found a [working alternative](https://marketplace.visualstudio.com/items?itemName=JuliaBay.spellcheck): working OK, but using an online API / web service => can't use offline...
- switched back to the initial extension, [found out](https://github.com/swyphcosmo/vscode-spellchecker/issues/22) that my problem was caused by a syntax error in my JSON vscode configuration file... => fixed it
- forked the extension's repo to https://github.com/adrienjoly/vscode-spellchecker, then cloned it locally
- moved the local repo to vscode's extensions directory, as explained [here](https://code.visualstudio.com/Docs/extensions/install-extension)
- found out that the extension's directory name had to match the extension's name (=> removed the `-fr` suffix)
- also found out that I needed to run `npm i` (to install dependencies), then ` npm run vscode:prepublish` (to compile the extension's source code) to make the extension show up in vscode's extensions list
- tried changing the extension's title from package.json => had to restart vscode to see the change in vscode's extensions list
- test: the local version of the extension works √
- found a french dictionary [there](https://github.com/wooorm/dictionaries/tree/master/dictionaries/fr_FR)
- realised that using npm to install it was not a solution, because the extension loads dictionaries from a specifically-defined directory only => moved FR dictionary files in that directory, and renamed them to match others.
- test: set "fr_FR" as language in the .vscode/spellchecker.json file of my sample workspace (directory) => the spell check did not work, found errors in vscode's console:

```
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:127 [Extension Host] Activating extension `swyphcosmo.spellchecker` failed: {1}.A.logExtensionHostMessage @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:127
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:127 [Extension Host] Activating extension `swyphcosmo.spellchecker` failed:  undefinedA.logExtensionHostMessage @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:127
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:127 [Extension Host] Here is the error stack:  undefined
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:109 Activating extension `swyphcosmo.spellchecker` failed: {1}.t.$localShowMessage @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:109
```

- tried removing FR dictionaries and reverting my workspace settings, but the same error was happening every time I restarted vscode... => I quit from there

**Comment by swyphcosmo** [comment]
You don't want to add the local repo to the vscode's extension directory. Because you're testing new functionality, you want to debug the extension from within VSCode.

* clone the repository
* run npm install to install all the typescript dependencies
* open the repository in VSCode
* press 'F5' to debug the extension

At this point, a new editor window will open with the local spellchecker extension enabled. 

I'm not sure what those errors are. They could have something to do with how the extension was installed. Here's how you can get more detailed information.

* Open /src/features/SpellCheckerProvider.ts
* On Line 11, change `false` to `true` to enable debug output. 

If you send me the log from the Developer Tools console, I can try to help out more.

**Comment by adrienjoly** [comment]
@swyphcosmo I did not know about all that, thank for having taken the time to explain!

I will probably plan another live coding session to do this, next week! I'll let you know!

**Comment by adrienjoly** [comment]
### Add a French spellchecker to Visual Studio Code (2nd try)

Live coding simultaneously from:

- https://twitch.tv/adrienjoly
- https://www.livecoding.tv/adrienjoly/

Steps:

- [x] Install and test existing extension: vscode-spellchecker 
- [x] Clone [my fork](https://github.com/adrienjoly/vscode-spellchecker) and test it locally (using F5)
- [x] Integrate a French dictionary (Hunspell .dic/.aff files) and test
- [x] Pull Request vscode-spellchecker

**Comment by adrienjoly** [comment]
@swyphcosmo Some progress and a PR, thanks to your advice!

Unfortunately, the French spell-checker is failing on some words:

<img width="506" alt="screen shot 2017-01-25 at 14 53 27" src="https://cloud.githubusercontent.com/assets/531781/22293332/7436ffc0-e30f-11e6-9947-5ae8ec90c460.png">

Also, I wasted a lot of time figuring out that I needed to install a git submodule for `hunspell-spellcheck`, so I took the liberty to add a `preinstall` hook to do that automatically in package.json.

Video of me doing this: [Make a FR spellchecker for Visual Studio Code](https://www.youtube.com/watch?v=WjHa2FK6Jjo) (Youtube)

**Comment by adrienjoly** [comment]
@swyphcosmo [Switching from the Hunspell submodule to Atom's node-spellcheck npm module](https://github.com/adrienjoly/vscode-spellchecker/commit/66b18efbc513265580f34d041da0a29d58c3eba5) solved my French spelling problems, and runs much faster.

One drawback is that the extension needs to be compiled separately for each platform, because [Atom's node-spellcheck npm module](https://github.com/atom/node-spellchecker) is a native module. And I had to use [electron-rebuild](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-easy-way) in order to compile accordingly to [VSCode's Electron version](https://code.visualstudio.com/docs/extensions/patterns-and-principles#_common-questions).

**Comment by adrienjoly** [comment]
@swyphcosmo I took the liberty to publish my fork of your extension on the marketplace: under the name [French spell checker](https://marketplace.visualstudio.com/items?itemName=adrienjoly.vscode-spellchecker-fr). (the corresponding forked repo is [there](https://github.com/adrienjoly/vscode-spellchecker))

I only tested it on Mac OS, and I doubt that it works on other platforms. I'm happy to collaborate if anybody wants to try it on another platform.

**Comment by swyphcosmo** [comment]
Just added dictionaries. Will be pushing a new release soon.

**Comment by adrienjoly** [comment]
awesome!

make sure that "j'aime" is not spotted as a spelling error. this is the reason why I had forked this extension.

**Comment by swyphcosmo** [comment]
Thanks for the suggestion. I was looking at the samples you provided, but wasn't sure which word should be spelled correctly. I know that one still caused an error, so I'll look into it.

**Comment by ghost** [comment]
I did try on Debian GNU/Linux. 
@adrienjoly mentioned he has only tested on MacosX so far.

and guess what?
not working... as expected.

I would like to help.
anybody may suggest clues to try out...

**Comment by swyphcosmo** [comment]
@pvincent. I haven't used @adrienjoly's fork of this extension as I'm not a French speaker. He's using a third party npm package called [spellchecker](https://www.npmjs.com/package/spellchecker) which supports native spell checker software. It should work on Linux, but you might need to install the native spellchecker through `apt`. I would suggest looking into that npm package or opening an issue on [@adrienjoly's fork](https://github.com/adrienjoly/vscode-spellchecker/tree/master/src) for help debugging your problem.

**Comment by ghost** [comment]
Thank you Michael.
I didn't notice there were other extensions on the same topic.
one of them works actually.

have a nice day

**Comment by adrienjoly** [comment]
Hi @pvincent! I'd be interested to know what extension you've ended up using, and how well it's working for you, if you don't mind :-)

**Comment by ghost** [comment]
* code-spell-checker
  * french-code-spell-checker

**Comment by adrienjoly** [comment]
I will check them out! Thanks!
