### ISSUE TITLE
suggestion: support aspell

### ISSUE THREAD

**Issue by OneOfOne** [swyphcosmo/vscode-spellchecker#36]
Like the title says, aspells seems to be more accurate and "smarter" in a lot of cases.

**Comment by swyphcosmo** [comment]
The problem with aspell is that it's a native tool. While supporting native tools will indeed be faster for the end user, it's a lot more difficult for me to support. VSCode requires distribution of all native binaries. There are many different OS configurations for me to test and deploy. At the moment, I don't plan on supporting native tools. However, when I find time in the coming weeks, I am planning to look into some alternative JavaScript based libraries which seem to out perform the hunspell port that I'm currently using.
