### ISSUE TITLE
configuration support in settings.json not working

### ISSUE THREAD

**Issue by btmurrell** [swyphcosmo/vscode-spellchecker#37]
Thanks for this extension. I see in your readme:

> As of v1.2.0, you can add any of the settings in spellchecker.json to the User Preferences settings.json. 

I have VS Code v1.10.1, and I just installed your extension v1.2.9 on Linux (mint).  According to your instructions, I add the following to my settings.json file:

```json
    "spellchecker.documentTypes": [
        "yaml"
    ],
    "spellchecker.ignoreWordsList": [
        "parmesean",
        "Quinoa",
        "saute"
    ],
```

I have a green squiggly line under these entries with a warning that says "Unknown configuration setting".  Am I doing it wrong?

I really would like to have this in my user settings because I want to edit one-off files that are not in a project folder.

![selection_008](https://cloud.githubusercontent.com/assets/634487/23494729/5ddb46b6-fec9-11e6-9b40-471ffb452353.jpg)

TIA for any assistance!

**Comment by swyphcosmo** [comment]
You're not doing anything wrong. You are seeing only warnings. It's just telling you that VSCode itself doesn't know what to do with those settings, but the extension will still process that file and use the settings. After you make changes, you will need to restart VSCode in order for the extension to process the changes.

**Comment by btmurrell** [comment]
thanks @swyphcosmo. I have restarted a couple of times, still get the warnings when i have the settings.json open.  however, it does recognize my ignoreWordsList if i have a pre-configurd settings.json at startup.  

but i think you have a bug here somewhere -- the warnings are still there, as i mentioned, and when I try to add new words to the dictionary, they don't get added to my settings.json.   

i will try it later on my mac.

**Comment by swyphcosmo** [comment]
The warnings will always be there, but they're just warnings, not errors. This is because they are not settings for the core of VSCode.

When you add new words to the dictionary, do you select 'Add to dictionary' or 'Always ignore'? Only the latter will add the words to the settings.json file.

**Comment by KarlAmort** [comment]
FWIW, VSCode does know about extensions' settings. (And it does work for me with spellchecker).
![screen shot 2017-04-05 at 12 44 44](https://cloud.githubusercontent.com/assets/10232033/24702166/e490324e-19fd-11e7-911b-9c7fdf29c26c.png)

Edit: Ah, I see this was recently changed. Thank you!
