### ISSUE TITLE
FAQ needed: need simple instructions as how to setup/ and how to use.

### ISSUE THREAD

**Issue by ipstone** [swyphcosmo/vscode-spellchecker#39]
Hello,

I just installed the spell checker in vscode, but have no idea how to use it/start it.

It says using hunspell - do we need to have hunspell available to use this? (proper installation?) I think we will need instructions on how to install.

Once installed, how to configure it? the default Create Spell Checker Setting file function isn't available yet. I got a error message "command 'spellchecker.createSettingsFile' not found.

Thx,

Ipstone

**Comment by swyphcosmo** [comment]
All the installation is handled when you install the extension. If there were extra steps, I would have documented them in the Readme.

I just checked the Create Spell Checker Settings File function with the extension version 1.2.9 and VSCode 1.10.1 on Ubuntu 16.04 without issue. What versions are you using? Did you make sure to restart VSCode before trying any of the functions? There are also instructions in the Readme about how to create this file manually.

If you provide the information, I'll try to help you debug the problem.

**Comment by ipstone** [comment]
Thanks, I am on Windows:  Code version 1.10.1 (32 bit) and latest extension version. I will test again and try manually create the setting file & follow the README.  thanks!
