### ISSUE TITLE
"Migrate and Delete spellcheck.json" doesn't work

### ISSUE THREAD

**Issue by KarlAmort** [swyphcosmo/vscode-spellchecker#41]
Since a recent update, I've gotten the notification mentioned in the title whenever the extension is initialised. Choosing "migrate and delete" does not actually do either. 

I've deleted the file manually and it solved the issue for me, but it's probably annoying others. I couldn't find any relevant messages in the developer console, but one clue may be that the file was actually `.vscode/spellchecker.json`, not `spellcheck.json`.

**Comment by swyphcosmo** [comment]
Thanks for catching this. The alert says 'spellcheck.json' but it's actually looking for 'spellchecker.json'. The issue was that I changed the text in the alert options during the display, but not in the callback. I'll be uploading an update in a few minutes.
