### ISSUE TITLE
Add support for German language

### ISSUE THREAD

**Issue by DFelten** [swyphcosmo/vscode-spellchecker#42]
Thanks for this great addon, it works great for the English language. In the moment I'm writing a paper with LaTeX in German and there I miss a spellchecker. 

It would be great if you could also add a German dictionary to your plugin. I tried to add a de_DE.aff and de_DE.dicto "swyphcosmo.spellchecker-1.2.13\languages", but now this isn't working (there is an error:
 spellchecker.setLanguage" not found). 

Thanks in advance!

**Comment by follnoob** [comment]
You need to add  German to src/features/SpellCheckerProvider.ts (or out/../*.js if the spellchecker extension is already installed) under ```private availableLanguages```.

This worked for me, but the linting didn't work as expected. I lints only the first few lines.

**Comment by swyphcosmo** [comment]
I apologize for not responding sooner.

You shouldn't need to modify `SpellCheckerProvider.ts`. This is only used if you use the 'Set Spell Checker Language' function. You should be able to set `spellchecker.language` is your user settings to `de_DE`. 

Unfortunately, I don't speak German, but if you can provide me with a simple text file in German with correct and misspelled words, I can try to debug what's going on with the issues of the entire document not being checked correctly.
