### ISSUE TITLE
Ignoring words not persistent between restarts

### ISSUE THREAD

**Issue by aleksandarristic** [swyphcosmo/vscode-spellchecker#43]
Ignored words, both 'Ignore' and 'Always ignore', are not persistent between editor restarts. Whenever I ignore a word it works perfectly fine while the editor is open. But every time I restart the editor, all the ignored words are marked as spelling errors again.

I'm using a mac for what it's worth. I'd be happy to provide you with any additional info needed to debug and solve this issue.

**Comment by jmakeig** [comment]
In my experience, the “Always Ignore” words are added to my `spellchecker.ignoreWordsList` array in my user preferences. Thus they are persistent. I can’t figure out what the logic is for simple “Ignore”. Even within the same editing session, this list seems to be forgotten intermittently. 

- SpellChecker v1.2.13
- VSCode v1.13.1
- macOS 10.12.5 (16F73)

**Comment by swyphcosmo** [comment]
'Ignore' is intended to save the word to your workspace settings while 'Always Ignore' will add the word to your global user settings file. On Windows, the workspace settings are stored in `workspace directory/.vscode/settings.json`. I imagine that the file is in a similar location on macOS. If this file is removed for some reason, the dictionary additions will be removed. 

Try to track down this file, and let me know if you see any additional issues with it.
