### ISSUE TITLE
Correction “light bulb” incorrectly appears on the line above the spelling error

### ISSUE THREAD

**Issue by jmakeig** [swyphcosmo/vscode-spellchecker#49]
In VSCode 1.17.2 the light-bulb icon to indicate a spelling error shows up on the line *above* the line in which the error occurs. The red squiggly underline shows up correctly and the interaction with the light bulb works as expected.

macOS 10.12.6
VSCode 1.17.2
SpellChecker 1.2.13

**Comment by jmakeig** [comment]
What is the actual name of the “light bulb” affordance?

**Comment by swyphcosmo** [comment]
@jmakeig Sorry that it took me so long to look into this. The lightbulb represents Code Actions (https://code.visualstudio.com/docs/editor/editingevolved#_code-action). From what I can tell, vscode puts the lightbulb on the line before the error/warning. I was unable to find a way to change it's location.
