### ISSUE TITLE
Should Misspelled Words Be Treated as Warnings Instead of Errors

### ISSUE THREAD

**Issue by designbystephen** [swyphcosmo/vscode-spellchecker#51]
Greetings and thanks for your extremely valuable extension!

I really like using this extension but ever since I recent change in vscode spelling errors are as visible as code lint errors, marking files and directories in red text.  I think for some projects this would be ok, but part of the contribution process for a project I manage mentions resolving linting errors before making a merge request... and with the added visibility of spelling errors it has become a bit more difficult to identify errors in the application.

Solution [Enhancement]:
1. Set the default severity to warning instead of error
415: let diag = new vscode.Diagnostic( lineRange, this.problemCollection[ token ], vscode.DiagnosticSeverity.Warning );

2. Allow users to optionally set a severity configuration to override this default.

I will see about making a merge request when I am at a personal computer today.

**Comment by swyphcosmo** [comment]
@designbystephen Sorry that it took me so long to get to this suggestion. I just added this feature with PR #62. I'll be releasing a new version of the extension to the marketplace soon.
