### ISSUE TITLE
Ability to spell check on save

### ISSUE THREAD

**Issue by TillKnollmann** [swyphcosmo/vscode-spellchecker#55]
It would be nice to have a flag such that a file is spell checked only if it is saved.

**Comment by noraj** [comment]
Spell check on save or spell check live but currently spell check manually by calling the command is not usable.

**Comment by swyphcosmo** [comment]
@TillKnollmann Sorry that it took me so long to look into this. Checking on save has been a feature since the first release of the extension. It's always enabled so no setting is required.
