### ISSUE TITLE
error spellcheck

### ISSUE THREAD

**Issue by guiprerod** [swyphcosmo/vscode-spellchecker#56]
- Extension Name: spellchecker
- Extension Version: 1.2.13
- OS Version: Windows_NT x64 10.0.15063
- VSCode version: 1.28.0-insider

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 89,
		"activateCallTime": 620,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by swyphcosmo** [comment]
Closing as there's not enough information to repro the error.
