### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pcfe** [swyphcosmo/vscode-spellchecker#57]
- Issue Type: `Performance`
- Extension Name: `spellchecker`
- Extension Version: `1.2.13`
- OS Version: `Linux x64 4.20.10-200.fc29.x86_64`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/pcfe/swyphcosmo.spellchecker-unresponsive.cpuprofile.txt
` :warning:

[swyphcosmo.spellchecker-unresponsive.cpuprofile.txt](https://github.com/swyphcosmo/vscode-spellchecker/files/2896589/swyphcosmo.spellchecker-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by pcfe** [comment]
both swyphcosmo/vscode-spellchecker#57 and DavidAnson/vscode-markdownlint#65 occurred during the same session. 10 other extensions remained responsive during that session.

**Comment by swyphcosmo** [comment]
@pcfe Sorry that it took me so long to look at this. I did look at your cpu profile, but I'm unable to debug this without additional information such as what file you were spellchecking when this occurred. The first check through a large file will take a while to check as it has to compare each word to the dictionary. After this scan, all the next scans are performed on a diff so the check operation is much faster.
