### ISSUE TITLE
Ability to hide error indicator in tab

### ISSUE THREAD

**Issue by MrDanielHarka** [swyphcosmo/vscode-spellchecker#68]
I'd like to hide the spell-check mistakes indicator from the tabs. How can I do that?

![Screenshot from 2021-04-13 00-07-45](https://user-images.githubusercontent.com/79216552/114469359-4315f900-9bed-11eb-810e-58af88de37bc.jpg)

**Comment by swyphcosmo** [comment]
Hi @MrDanielHarka. Apologies for the very delayed response.

I don't think this is something that can be turned off on a per-extension basis. I found [this suggestion](https://github.com/microsoft/vscode/issues/113239#issuecomment-754145381) on how to disable all decoration badges.
