### ISSUE TITLE
Bug with Ignored Word Lists - Can't use both global and local lists.

### ISSUE THREAD

**Issue by Lejero** [swyphcosmo/vscode-spellchecker#69]
It appears that the local workspace level ignoredWordsList is overriding looking in the global list associated with the app. Thus, if the property is not set locally, then the global list will apply, but as soon as a locally ignored word is added the spelling errors covered by the global list reappear.

This is getting in the way, say, with some fiction writing I was doing where I wanted a few names and such to be ignored locally but they were too esoteric to make sense to ignore in everything else I worked in.

I'm working on an M1 Macbook Air running MacOS Catalina but not sure if that has any bearing.

**Comment by swyphcosmo** [comment]
Hi Lejero. I'm sorry for the very delayed response.

Unfortunately, this is how vscode works. From https://code.visualstudio.com/docs/getstarted/settings:

> Workspace settings are specific to a project and can be shared across developers on a project. Workspace settings override user settings.

In the plugin api, only the [merged settings](https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration) can be accessed, not the individual user and workspace settings.
