### ISSUE TITLE
Words that start with capitals should be ignored

### ISSUE THREAD

**Issue by simonv3** [swyphcosmo/vscode-spellchecker#70]
I feel like proper names should be ignored, eg. Boggs, for spelling errors?

**Comment by swyphcosmo** [comment]
Apologies for such a late response. 

The problem here is how to detect if a word is a proper name or if it's a non-proper name that's at the beginning of a sentence. 

You can add a custom regular expression to ignore capitalized words:

```
"spellchecker.ignoreRegExp": [
	"/[A-Z][a-z]*/g",
]
```
