### ISSUE TITLE
Emit info instead of warnings/errors

### ISSUE THREAD

**Issue by gediminasel** [swyphcosmo/vscode-spellchecker#71]
![image](https://user-images.githubusercontent.com/21194519/140803030-59e500b2-a788-436c-8700-491ff51d7ea2.png)
Maybe this could be a dropdown and allow choosing `Info` as well as `Warning` and `Error`?

**Comment by swyphcosmo** [comment]
Thanks for the suggestion. I just opened #78 to implement this. I'll get a new release out soon.
