### ISSUE TITLE
Ability to ignore by filename

### ISSUE THREAD

**Issue by phil-the-dev** [swyphcosmo/vscode-spellchecker#72]
When editing my VS Code's settings.json, I'm seeing a lot of misspellings because of extension names. it would be neat if I could do something like `ignoreFilenames: ["settings.json", "package.json"]`

**Comment by tjex** [comment]
this exists already. check under Configuration File in the readme.
(but I'm having trouble getting it to work actually)
If it works for you, could you paste in here the code block, maybe my syntax is wrong.

Also, according to readme .documentTypes should limit the files which spellchecker works on, but it also doesn't work for me.

```
    "spellchecker.documentTypes": [
        "markdown", 
        "plaintext"
    ],
    "spellchecker.ignoreFileExtensions": [
        ".py", 
    ],
```

**Comment by phil-the-dev** [comment]
Well, I'm not talking about ignoring file types, but specific filename + extension; so I can get my translation json files spellchecked, but the VS Code User Setting json not spellchecked.

**Comment by tjex** [comment]
ahhhh right, sorry. No idea about that then

**Comment by swyphcosmo** [comment]
Thanks for the suggestion. I just added this feature in #81. I'll be releasing a new version of the extension soon.
