### ISSUE TITLE
Enhancement Request > RH click menu item to "add word to user-defined dictionary"

### ISSUE THREAD

**Issue by ghost** [swyphcosmo/vscode-spellchecker#74]
Hi there, I'd like to thank you for your work on the extension, it works really well.

This enhancement request is based on spell-check behaviour in other applications, including Atom editor and even MS Word.

The current functionality will spell-check, but I can't add the word to the user-defined dictionary without manually opening the file and adding it there. This interrupts the flow of writing.

It would be really useful to be able to add a highlighted word to the user-defined dictionary from the editor (say in a RH-click menu), rather than manually adding it to a config file.

**Comment by swyphcosmo** [comment]
Hi @ljsinclair. This feature is already supported. In the quick fix menu, there are options after the suggested corrections to "ignore" and "always ignore" the word. "Ignore" will add the word to `spellchecker.ignoreWordsList` in the workspace config, and "always ignore" will add the word to the same variable in the user config.

![image](https://user-images.githubusercontent.com/7516713/179578992-4782dc1a-7d01-49f0-9ba1-c1449dc5efaf.png)
