### ISSUE TITLE
Spellchecker doesn't seem to work outside of a workspace

### ISSUE THREAD

**Issue by jmmv** [swyphcosmo/vscode-spellchecker#8]
I just installed the vscode-spellchecker plugin and was trying to make it work without a workspace, because I was editing a single Markdown document.

The spellchecker didn't work after restarting VSCode (1.4) on OS X to enable the plugin. I tried to create a `spellchecker.json` file under `~/.vscode` to see if that was missing, but it didn't help. In the end, I moved my document into a workspace and things worked.

I created the workspace by making a `.vscode` directory in a brand new directory and putting the `spellchecker.json` file into it.

Is this a known issue? The documentation didn't say anything about requiring a workspace, and requiring one seems suboptimal for the use case I mentioned above (standalone file editing).

**Comment by swyphcosmo** [comment]
This never used to be an issue. Very weird. I'll check it out in the next couple days to see if I can figure out why.

**Comment by swyphcosmo** [comment]
I finally got time to check this out. I found the error and fixed it yesterday. I'll get a new version of the extension uploaded this evening.

**Comment by swyphcosmo** [comment]
I just uploaded `v1.2.0` which should fix your problem. Let me know if you run into any other issues.
